services:
  stripe-api:
    build: .
    container_name: stripe-api
    ports:
      - "9000:${PORT}"
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      PORT: ${PORT}
      SECRET_KEY: ${SECRET_KEY}
    command: npm start
