services:
  production:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        NODE_ENV: production
    container_name: stripe-api-production
    ports:
      - '${PORT_OUT}:${PORT_IN}'
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      PORT: ${PORT_IN}
      SECRET_KEY: ${SECRET_KEY}
    command: ['npm', 'run', 'start:prod']
