FROM node:22-alpine AS builder
LABEL authors="arthurzakharov"
WORKDIR /app
COPY package*.json ./
RUN npm install
RUN npm install -g typescript
COPY . .
RUN npm run build

FROM node:22-alpine
COPY package*.json ./
RUN npm ci --production
COPY --from=builder /app/dist ./dist
EXPOSE 3000
CMD npm run start:prod
