services:
  development:
    build:
      context: .
      args:
        NODE_ENV: development
    container_name: stripe-api-dev
    ports:
      - "9000:${PORT}"
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      PORT: ${PORT}
      SECRET_KEY: ${SECRET_KEY}
    command: npm run start:dev
